export const SEARCH_ROOM = 'SEARCH_ROOM';

export const SELECT_FLOOR = 'SELECT_FLOOR';
export const SELECT_ROOM = 'SELECT_ROOM';

export const SELECT_AREA = 'SELECT_AREA';

export const FETCH_OFFICE_BEGIN = 'FETCH_OFFICE_BEGIN';
export const FETCH_OFFICE_SUCCESS = 'FETCH_OFFICE_SUCCESS';
export const FETCH_OFFICE_FAILURE = 'FETCH_OFFICE_FAILURE';

export const FETCH_USER_OFFICE_SUCCESS = 'FETCH_USER_OFFICE_SUCCESS';
export const FETCH_USER_OFFICE_BEGIN = 'FETCH_USER_OFFICE_BEGIN';
export const FETCH_USER_OFFICE_FAILURE = 'FETCH_USER_OFFICE_FAILURE';

export const FETCH_USER_BEGIN = 'FETCH_USER_BEGIN';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const ADDRESS_CHANGED = 'ADDRESS_CHANGED';
export const FLOOR_CHANGED = 'FLOOR_CHANGED';
